#!/bin/bash

HEAD_NODE=$1
TCP_PORTS="22,80,443,6783"
UDP_PORTS="6783,6784"
DOCKER_HOST="unix:///var/run/user-docker.sock"

WEAVE_CONFIG=/var/lib/rancher/conf/cloud-config.d/weave_config.yml
WEAVE_SERVICE=/var/lib/rancher/conf/weave.yml

DOCKER_ARGS="[$(sudo ros config get rancher.docker.args | grep -v unix:/// | sed -e 's/^- //g' | sed -e 's/.$/&, /' | xargs echo -n)$DOCKER_HOST]"
ros config set rancher.docker.args "$DOCKER_ARGS"

system-docker rm weave
ros s delete $WEAVE_SERVICE
cat > $WEAVE_SERVICE <<WEAVESERVICE
weave:
  image: nhzio/ros-weave:latest
  container_name: weave
  privileged: true
  net: host
  stdin_open: true
  tty: true
  labels:
    io.rancher.os.scope: system
    io.rancher.os.after: docker,console
  environment:
    TCP_PORTS: $TCP_PORTS
    UDP_PORTS: $UDP_PORTS
    HEAD_NODE: $HEAD_NODE
    DOCKER_HOST: $DOCKER_HOST
  volumes_from:
    - /var/run:/var/run
WEAVESERVICE

ros s enable $WEAVE_SERVICE
ros s pull weave
system-docker pull nhzio/ros-weave:latest
ros s create

cat > $WEAVE_CONFIG <<'WEAVECONFIG'
write_files:
- path: /opt/rancher/bin/start.sh
  owner: root
  permissions: "0755"
  content: |
    #!/bin/sh
    sudo ln -sf /var/run/user-docker.sock /var/run/docker.sock

- path: /usr/bin/weave
  owner: root
  permissions: "0755"
  content: |
    #!/bin/bash
    docker -H unix:///var/run/user-docker.sock run --rm -i -t -v /var/run:/var/run nhzio/ros-weave:latest weave "$@"
WEAVECONFIG
